export const FETCH_MOVIES_LIST_REQUEST = 'FETCH_MOVIES_LIST_REQUEST';
export const FETCH_MOVIES_LIST_SUCCESS = 'FETCH_MOVIES_LIST_SUCCESS';
export const FETCH_MOVIES_LIST_FAILURE = 'FETCH_MOVIES_LIST_FAILURE';

export const FETCH_SINGLE_MOVIE_DETAILS_REQUEST = 'FETCH_SINGLE_MOVIE_DETAILS_REQUEST';
export const FETCH_SINGLE_MOVIE_DETAILS_SUCCESS = 'FETCH_SINGLE_MOVIE_DETAILS_SUCCESS';
export const FETCH_SINGLE_MOVIE_DETAILS_FAILURE = 'FETCH_SINGLE_MOVIE_DETAILS_FAILURE';
